fix: correct some issues with CI/CD jobs, move build to `tox`
This commit introduces `tox` for our builds.  It replaces the
previous approach of directly creating a virtualenv and defers
that to `tox`, which will create multiple virtualenvs to allow
testing of multiple versions of python.

`tox` is used in a wide variety of high-visibility python projects
such as pytest, Django Channels, Twisted, etc.  In addition to
allowing us to more easily test multiple python versions, it
sounds like it will actual install the built package into the
virtualenvs and then run the tests against that, rather than
running against the source, so it should give us better coverage
of the packaging itself.

It also gives us an easy pattern for adding linting and some other
tasks in subsequent commits.

Also in this commit, we make some changes to the CI/CD github
actions:
1. Previously the tests were only being run in the CI job, which,
   on push, was running in parallel to the CD job.  This meant that
   it was possible for the tests to fail but we would still publish
   the new artifact.  This is now fixed, the CD job also runs the
   tests.
2. Build commands switched to tox
3. CD job no longer runs on push; we will manually run it to do
   releases on a more deliberate schedule for now.

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,11 +1,6 @@
 name: CD
 
-# If this is made manual, then also update the pull_request.yml, to run builds
-# on main on merge.
 on:
-  push:
-    branches: [ main ]
-
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
@@ -39,14 +34,19 @@ jobs:
       - uses: actions/checkout@v2
 
       - name: Setup Python
-        uses: actions/setup-python@v2
+        uses: "gabrielfalcao/pyenv-action@v5"
         with:
-          python-version: '3.x'
+          versions: 3.8.12, 3.9.10
 
-      - name: Install python dependencies
+      - name: Build package and run tests
         run: |
+          pyenv local 3.8.12 3.9.10
+          tox
+
+      - name: Prepare to publish
           python -m pip install --upgrade pip
           pip install setuptools wheel twine build
+
       - name: Configure Artifactory publish credentials
         run: |
           set -e
@@ -63,8 +63,8 @@ jobs:
           export MOMENTO_SDK_VERSION="${{needs.release.outputs.version}}"
           if [ -z "$MOMENTO_SDK_VERSION"]
           then
-            echo "Using default version"
-            export MOMENTO_SDK_VERSION="0.0.dev"`date +%s`
+            echo "Unable to determine SDK version!  Exiting!"
+            exit 1
           fi
           echo "MOMENTO_SDK_VERSION=${MOMENTO_SDK_VERSION}"
           python -m build
